### ISSUE TITLE
Ao evocar FastSaftEncrypt, obtenho o erro [JCE cannot authenticate the provider BC]

### ISSUE THREAD

**Issue by JulioNobre** [assoft-portugal/CryptoSAF-T-SAF-T-Utils#4]
Quando tento cifrar um ficheiro já canonizado dá-me o erro apresentado a seguir ao comando.

java -jar jar\FastSaftEncrypt.jar-jar-with-dependencies.jar E sge2019.xml.can.xml sge2019.xml.can.xml-cifrado.xml "/DlxNRtpwRMA5Awa7qobXA=="  "4rbgWRGnJWENAoXGiJrpEQ=="

Start
Mode ENCRYPT
Input File sge2019.xml.can.xml
Output File sge2019.xml.can.xml-cifrado.xml
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:722)
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:642)
        at pt.cryptosaft.demo.FastSaftEncrypt.cipherInitialization(FastSaftEncrypt.java:312)
        at pt.cryptosaft.demo.FastSaftEncrypt.main(FastSaftEncrypt.java:127)
Caused by: java.util.jar.JarException: file:/D:/Documentos/Assoft/CryptoSaft/Utils/CryptoSAF-T-SAF-T-Utils/jar/FastSaftE
ncrypt.jar-jar-with-dependencies.jar has unsigned entries - META-INF/services/java.security.Provider
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:192)
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:220)
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:718)
        ... 3 more

**Comment by cryptolopes** [comment]
> Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC

Qual é a versão do JAVA @JulioNobre?

Os últimos JARs foram compilados para a versão 15.
Sugiro usar o [OpenJDK](https://jdk.java.net/15/).

https://github.com/assoft-portugal/CryptoSAF-T-SAF-T-Utils/blob/1bf2a87b2d8d83c674e008a06f503135669bc48e/pom.xml#L66-L70

**Comment by JulioNobre** [comment]
De facto, através do Java.exe do OpenJDK 15, o processo de cifra já foi bem-sucedido.

Obrigado pela dica! :-)
